import streamlit as st
from langchain_ollama import OllamaLLM
from langchain_core.prompts import PromptTemplate
from typing import List, Dict, Any, Generator
from langchain_core.documents import Document

@st.cache_resource
def get_llm(model_name: str = "llama3.2:3b") -> OllamaLLM:
    """
    Load the Ollama LLM model lazily and cache it using st.cache_resource.
    Allows user to switch between llama3.2:3b (high quality) and llama3.2:1b (high speed).
    """
    return OllamaLLM(
        model=model_name, 
        base_url="http://localhost:11434", 
        temperature=0.2
    )

def handle_llm_exception(e: Exception, model_name: str) -> str:
    """
    Parses LLM exception into a student-friendly, readable format for debugging.
    """
    error_msg = str(e)
    # Check for common connection errors
    if "connection" in error_msg.lower() or "refused" in error_msg.lower() or "actively refused" in error_msg.lower():
        return (
            "Error: Could not connect to Ollama. Please make sure the Ollama application "
            "is running on your system (http://localhost:11434)."
        )
    # Check for missing models
    elif "not found" in error_msg.lower() or "404" in error_msg.lower():
        return (
            f"Error: Ollama model '{model_name}' was not found.\n"
            f"Please open your terminal/command prompt and run:\n"
            f"  ollama pull {model_name}"
        )
    else:
        return f"Error communicating with Ollama: {error_msg}"

def generate_answer(question: str, context_chunks: List[Document], model_name: str = "llama3.2:3b") -> str:
    """
    Combines retrieved context chunks and the user's question,
    formats them into a strict, concise RAG prompt, and calls Ollama to generate a answer.
    """
    if not context_chunks:
        return "I could not find any relevant information in the uploaded notes to answer your question. Please make sure the notes are uploaded first."

    # Format the context text nicely with page numbers
    formatted_context_list = []
    for doc in context_chunks:
        page_num = doc.metadata.get("page_num", "Unknown")
        source = doc.metadata.get("source", "Notes")
        formatted_context_list.append(f"[Source: {source}, Page {page_num}]:\n{doc.page_content}")
        
    context_text = "\n\n---\n\n".join(formatted_context_list)

    # Short and concise RAG prompt template to reduce processing time
    prompt_template = """You are ScholarAI, an intelligent college study assistant.
Answer the user's question using ONLY the provided context blocks extracted from their notes.
If the answer cannot be found in the context, reply that you could not find the answer in the uploaded notes. Do NOT use external knowledge.

Context:
{context}

Question:
{question}

Answer:"""

    prompt = PromptTemplate(
        input_variables=["context", "question"],
        template=prompt_template
    )

    llm = get_llm(model_name)
    formatted_prompt = prompt.format(context=context_text, question=question)
    
    try:
        response = llm.invoke(formatted_prompt)
        return response.strip()
    except Exception as e:
        return handle_llm_exception(e, model_name)

def stream_answer(question: str, context_chunks: List[Document], model_name: str = "llama3.2:3b") -> Generator[str, None, None]:
    """
    Yields answer tokens in real-time as they are generated by the local LLM.
    This provides an interactive typing effect and drops perceived latency to zero.
    """
    if not context_chunks:
        yield "I could not find any relevant information in the uploaded notes to answer your question. Please make sure the notes are uploaded first."
        return

    formatted_context_list = []
    for doc in context_chunks:
        page_num = doc.metadata.get("page_num", "Unknown")
        source = doc.metadata.get("source", "Notes")
        formatted_context_list.append(f"[Source: {source}, Page {page_num}]:\n{doc.page_content}")
        
    context_text = "\n\n---\n\n".join(formatted_context_list)

    # Short and concise RAG prompt template to reduce processing time
    prompt_template = """You are ScholarAI, an intelligent college study assistant.
Answer the user's question using ONLY the provided context blocks extracted from their notes.
If the answer cannot be found in the context, reply that you could not find the answer in the uploaded notes. Do NOT use external knowledge.

Context:
{context}

Question:
{question}

Answer:"""

    prompt = PromptTemplate(
        input_variables=["context", "question"],
        template=prompt_template
    )

    llm = get_llm(model_name)
    formatted_prompt = prompt.format(context=context_text, question=question)
    
    try:
        # Stream response token-by-token
        for chunk in llm.stream(formatted_prompt):
            yield chunk
    except Exception as e:
        yield handle_llm_exception(e, model_name)
